### ISSUE TITLE
ValueError: x and y must have same first dimension, but have shapes (8066122,) and (4033061, 2)

### ISSUE THREAD

**Issue by WestbrookZero** [Vatsha/Audio-Signal-Similarity-Using-mfcc-and-crosscorellation#1]
(4033061, 2)
(4033061, 2)
sample_rate1 : 44100
audio1 size : 8066122
Time Duration :  182.90526077097505
sample_rate2 : 44100
audio2 size : 8066122
Time Duration :  182.90526077097505
Traceback (most recent call last):
  File "D:/Projects/SpeechCompare/Audio-Signal-Similarity-Using-mfcc-and-crosscorellation-master/audio_signal_similarity.py", line 50, in <module>
    plt.plot(t1,audio1)
  File "D:\InstallPath\Develop\Anaconda3\5.3.1\envs\ComplexYOLO\lib\site-packages\matplotlib\pyplot.py", line 2763, in plot
    is not None else {}), **kwargs)
  File "D:\InstallPath\Develop\Anaconda3\5.3.1\envs\ComplexYOLO\lib\site-packages\matplotlib\axes\_axes.py", line 1646, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "D:\InstallPath\Develop\Anaconda3\5.3.1\envs\ComplexYOLO\lib\site-packages\matplotlib\axes\_base.py", line 216, in __call__
    yield from self._plot_args(this, kwargs)
  File "D:\InstallPath\Develop\Anaconda3\5.3.1\envs\ComplexYOLO\lib\site-packages\matplotlib\axes\_base.py", line 342, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (8066122,) and (4033061, 2)

**Comment by Vatsha** [comment]
matplotlib package is missing, that's why you are getting such error. you can use google colab and run this code there . You don't have such problem there.
